import React, { useState } from 'react';
import { useApi } from '../context/ApiContext';
import { getMethodColor } from '../utils/formatters';
import {
  BookOpen,
  X,
  Copy,
  Check,
  Download,
  FileText,
  FolderOpen,
  Code2,
  Sparkles,
  ExternalLink,
} from 'lucide-react';

export const ApiDocsModal = ({ isOpen, onClose }) => {
  const { collections, activeRequest } = useApi();
  const [selectedColId, setSelectedColId] = useState(collections[0]?._id || 'active');
  const [viewMode, setViewMode] = useState('preview'); // 'preview' or 'markdown'
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const currentCollection = collections.find((c) => c._id === selectedColId);

  // Generate Markdown representation
  const generateMarkdown = () => {
    let md = '';

    if (selectedColId === 'active' || !currentCollection) {
      md += `# API Documentation: ${activeRequest.name || 'API Request'}\n\n`;
      md += `> Automatically generated by APITester Studio on ${new Date().toLocaleDateString()}\n\n`;
      md += `### Endpoint\n\n`;
      md += `\`${activeRequest.method || 'GET'}\` **${activeRequest.url || '/'}**\n\n`;

      if (activeRequest.params && activeRequest.params.filter((p) => p.enabled && p.key).length > 0) {
        md += `#### Query Parameters\n\n`;
        md += `| Parameter | Value | Description |\n`;
        md += `| :--- | :--- | :--- |\n`;
        activeRequest.params
          .filter((p) => p.enabled && p.key)
          .forEach((p) => {
            md += `| \`${p.key}\` | \`${p.value}\` | ${p.description || '-'} |\n`;
          });
        md += `\n`;
      }

      if (activeRequest.headers && activeRequest.headers.filter((h) => h.enabled && h.key).length > 0) {
        md += `#### Request Headers\n\n`;
        md += `| Header | Value | Description |\n`;
        md += `| :--- | :--- | :--- |\n`;
        activeRequest.headers
          .filter((h) => h.enabled && h.key)
          .forEach((h) => {
            md += `| \`${h.key}\` | \`${h.value}\` | ${h.description || '-'} |\n`;
          });
        md += `\n`;
      }

      if (activeRequest.rawBody) {
        md += `#### Request Body (${activeRequest.bodyType || 'json'})\n\n`;
        md += `\`\`\`json\n${activeRequest.rawBody}\n\`\`\`\n\n`;
      }

      if (activeRequest.testCases && activeRequest.testCases.length > 0) {
        md += `#### Automated Tests / Assertions\n\n`;
        activeRequest.testCases.forEach((tc) => {
          md += `- [x] **${tc.name}** (Type: \`${tc.type}\`, Expected: \`${tc.expectedValue}\`)\n`;
        });
        md += `\n`;
      }

      return md;
    }

    // Collection documentation
    md += `# ${currentCollection.name} — API Documentation\n\n`;
    if (currentCollection.description) {
      md += `${currentCollection.description}\n\n`;
    }
    md += `*Generated by APITester Studio on ${new Date().toLocaleDateString()}*\n\n`;
    md += `## Table of Endpoints\n\n`;

    const reqs = currentCollection.requests || [];
    reqs.forEach((r, idx) => {
      md += `${idx + 1}. [\`${r.method}\` ${r.name || r.url}](#endpoint-${idx + 1})\n`;
    });
    md += `\n---\n\n`;

    reqs.forEach((r, idx) => {
      md += `### <a id="endpoint-${idx + 1}"></a> ${idx + 1}. ${r.name || 'Endpoint'}\n\n`;
      md += `\`${r.method || 'GET'}\` **${r.url || '/'}**\n\n`;

      if (r.description) {
        md += `${r.description}\n\n`;
      }

      if (r.params && r.params.length > 0) {
        md += `#### Query Parameters\n\n`;
        md += `| Key | Value | Description |\n| :--- | :--- | :--- |\n`;
        r.params.forEach((p) => {
          md += `| \`${p.key}\` | \`${p.value}\` | ${p.description || '-'} |\n`;
        });
        md += `\n`;
      }

      if (r.headers && r.headers.length > 0) {
        md += `#### Request Headers\n\n`;
        md += `| Header | Value |\n| :--- | :--- |\n`;
        r.headers.forEach((h) => {
          md += `| \`${h.key}\` | \`${h.value}\` |\n`;
        });
        md += `\n`;
      }

      if (r.body || r.rawBody) {
        md += `#### Request Payload\n\n\`\`\`json\n${r.body || r.rawBody}\n\`\`\`\n\n`;
      }

      md += `---\n\n`;
    });

    return md;
  };

  const markdownContent = generateMarkdown();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(markdownContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error(err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const title = (currentCollection ? currentCollection.name : 'api-request')
      .toLowerCase()
      .replace(/[^a-z0-9]/g, '-');
    link.download = `${title}-api-docs.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl shadow-2xl overflow-hidden flex flex-col text-xs max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-xl bg-sky-500/15 text-sky-400 border border-sky-500/25">
              <BookOpen className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-100 text-sm">Interactive API Documentation Generator</h3>
              <p className="text-[11px] text-slate-400">
                Generate clean, publication-ready Markdown docs for GitHub, Notion, or developer portals
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-200 rounded-lg hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Toolbar Bar */}
        <div className="px-6 py-3 bg-slate-950/70 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2">
            <label className="text-slate-400 font-semibold">Select Scope:</label>
            <select
              value={selectedColId}
              onChange={(e) => setSelectedColId(e.target.value)}
              className="bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 text-slate-200 focus:outline-none focus:border-sky-500 text-xs cursor-pointer"
            >
              <option value="active">Active Workbench Request</option>
              {collections.map((c) => (
                <option key={c._id} value={c._id}>
                  {c.name} ({c.requests?.length || 0} endpoints)
                </option>
              ))}
            </select>
          </div>

          <div className="flex items-center gap-2">
            {/* View Mode Toggle */}
            <div className="flex bg-slate-900 rounded-lg p-0.5 border border-slate-800 text-[11px]">
              <button
                type="button"
                onClick={() => setViewMode('preview')}
                className={`px-3 py-1 rounded-md transition cursor-pointer ${
                  viewMode === 'preview'
                    ? 'bg-sky-600 text-white font-semibold shadow-xs'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Visual Preview
              </button>
              <button
                type="button"
                onClick={() => setViewMode('markdown')}
                className={`px-3 py-1 rounded-md transition cursor-pointer ${
                  viewMode === 'markdown'
                    ? 'bg-sky-600 text-white font-semibold shadow-xs'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Raw Markdown
              </button>
            </div>

            {/* Copy Button */}
            <button
              type="button"
              onClick={handleCopy}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700/80 transition flex items-center gap-1.5 cursor-pointer font-medium"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
              <span>{copied ? 'Copied' : 'Copy MD'}</span>
            </button>

            {/* Download Button */}
            <button
              type="button"
              onClick={handleDownload}
              className="px-3.5 py-1.5 rounded-lg bg-sky-600 hover:bg-sky-500 text-white font-semibold transition flex items-center gap-1.5 shadow-sm shadow-sky-600/25 cursor-pointer active:scale-95"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export .md</span>
            </button>
          </div>
        </div>

        {/* Content Pane */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950">
          {viewMode === 'preview' ? (
            /* Visual Documentation Preview */
            <div className="space-y-6 max-w-3xl mx-auto">
              {/* Doc Title Banner */}
              <div className="p-6 rounded-2xl bg-gradient-to-br from-slate-900 to-slate-950 border border-slate-800 space-y-2">
                <div className="flex items-center gap-2 text-sky-400 text-xs font-semibold">
                  <Sparkles className="w-4 h-4" />
                  <span>API Specification Reference</span>
                </div>
                <h1 className="text-xl font-bold text-white tracking-tight">
                  {selectedColId === 'active' || !currentCollection
                    ? activeRequest.name || 'API Workbench Request'
                    : currentCollection.name}
                </h1>
                <p className="text-xs text-slate-400 leading-relaxed">
                  {currentCollection?.description ||
                    'Comprehensive documentation including parameters, request headers, payload body schemas, and assertions.'}
                </p>
              </div>

              {/* Endpoints Documentation Cards */}
              <div className="space-y-4">
                {(selectedColId === 'active' || !currentCollection
                  ? [activeRequest]
                  : currentCollection.requests || []
                ).map((r, idx) => (
                  <div
                    key={idx}
                    className="p-5 rounded-xl bg-slate-900/70 border border-slate-800 space-y-4 shadow-sm"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <span
                          className={`px-2.5 py-1 rounded font-mono font-bold text-xs border ${getMethodColor(
                            r.method
                          )}`}
                        >
                          {r.method || 'GET'}
                        </span>
                        <h3 className="font-bold text-sm text-slate-100">{r.name || 'Endpoint'}</h3>
                      </div>
                      <span className="text-[11px] font-mono text-slate-500">#{idx + 1}</span>
                    </div>

                    <div className="p-2.5 rounded-lg bg-slate-950 font-mono text-xs text-slate-300 border border-slate-800 break-all select-all">
                      {r.url || '/'}
                    </div>

                    {/* Query Params */}
                    {r.params && r.params.filter((p) => p.enabled && p.key).length > 0 && (
                      <div className="space-y-1.5">
                        <h4 className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                          Query Parameters
                        </h4>
                        <div className="border border-slate-800 rounded-lg overflow-hidden">
                          <table className="w-full text-left text-xs">
                            <thead className="bg-slate-950 text-slate-400 text-[10px] uppercase font-semibold">
                              <tr>
                                <th className="p-2">Key</th>
                                <th className="p-2">Value</th>
                                <th className="p-2">Description</th>
                              </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-800/60 font-mono text-[11px]">
                              {r.params
                                .filter((p) => p.enabled && p.key)
                                .map((p, pIdx) => (
                                  <tr key={pIdx}>
                                    <td className="p-2 text-sky-400 font-bold">{p.key}</td>
                                    <td className="p-2 text-slate-300">{p.value}</td>
                                    <td className="p-2 text-slate-400 font-sans">{p.description || '-'}</td>
                                  </tr>
                                ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    )}

                    {/* Request Body */}
                    {(r.rawBody || r.body) && (
                      <div className="space-y-1.5">
                        <h4 className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                          Request Body Schema
                        </h4>
                        <pre className="p-3 bg-slate-950 rounded-lg border border-slate-800 font-mono text-xs text-amber-200 overflow-x-auto whitespace-pre-wrap">
                          {r.rawBody || r.body}
                        </pre>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ) : (
            /* Raw Markdown View */
            <textarea
              readOnly
              value={markdownContent}
              rows={24}
              className="w-full h-full bg-slate-950 font-mono text-xs text-slate-200 p-4 rounded-xl border border-slate-800 focus:outline-none resize-none leading-relaxed select-all"
            />
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950 flex items-center justify-between text-slate-400 text-[11px]">
          <span>Exported markdown is compatible with GitHub, GitLab, MkDocs, and Swagger documentation specs.</span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-750 text-slate-200 transition cursor-pointer font-medium"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
